### ISSUE TITLE
working code doesn't pass specs because of the very specific order in which `over?` and `turn` must be called

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/tic-tac-toe-rb#11]
was pretty frustrating to have a working tic tac toe game that the tests would just loop infinitely on.

**Comment by aturkewi** [comment]
@loganhasson ended up adding a note in the readme about the possibility of a 'stack level too deep' error so that they can mroe easily debug it. 

I know the tests are a bit rigid right now, but ended up leaving these incremental tests in place to really help guide students to a specific answer rather than allowing them to get too lost in the multitude of working answers.
