### ISSUE TITLE
coverage report can not be opened.

### ISSUE THREAD

**Issue by scottwansz** [learn-co-curriculum/tic-tac-toe-rb#33]
when try to open the coverage report, shows error as:

Finished in 0.07702 seconds (files took 0.30207 seconds to load)
37 examples, 0 failures
Coverage report generated for RSpec to /home/nitrous/code/labs/tic-tac-toe-rb-002/coverage. 2260 / 3925 LOC (57.58%) covered.
➜  tic-tac-toe-rb-002 git:(master) ✗ open coverage/index.html
Couldn't get a file descriptor referring to the console

**Comment by AnnJohn** [comment]
Hi @scottwan thanks again for raising this. We'll look into it, and as always, if you use the Ask a Question tool in Learn, someone will help you out right away. Thanks.

**Comment by aturkewi** [comment]
Hey @scottwan thanks for raising this issue. The `open` command only worked if you were going through this lab on a Mac and that command didn't work on Nitrous. We're now actually recommending that people start using the Learn IDE rather than the Nitrous IDE and that will solve this problem. 
If you still want to view the page in Nitrous though, you can use these steps to view a webpage: https://community.nitrous.io/docs/preview-a-static-html-page
