### ISSUE TITLE
#player_move

### ISSUE THREAD

**Issue by mat0829** [learn-co-curriculum/tic-tac-toe-rb#68]
On the Tic Tac Toe in Ruby lab they have us copy and paste almost every Tic Tac Toe method we have built along the way, which takes a significant amount of time, and for no reason I can tell, since we already learned this method and defined it, they renamed it from #move to #player_move with no reason. This makes students spend a significant amount of time attempting to find this previously defined method, like ALL of the others we were to copy and paste, rather than to just keep it as the #move for copy and pasting, again, like ALL of the others. This is supposed to be about #play, not about whether or not we can be tricked. It cost me alot of time when it was completely unnecessary. I already figured out that method. It was pointless struggle just so I can get to the part of the lab that is new. Very frustrating and my first real gripe about this course. I suggest either to pick one method name and carry it to all relating lessons. This stuff is complicated enough without being tricked pointlessly.

**Comment by cjbrock** [comment]
Hi @mat0829! 

The reason that we renamed that method was intentional, and not meant to cause frustration. If you look at the notes in the lesson, you'll see:

> #player_move
> Your #player_move method must take in three arguments: 1) the board array, 2) the index in the board array that the player would like to fill out with an "X" or and "O", and 3) the player's character (either "X" or "O"). We previously had you write this method with a default argument of "X" for the third argument, but that is no longer needed.

Since we adjusted the method significantly (removing the default third argument), we also changed the name as a signifier that something is different about the method, and that might be the reason that you aren't passing the tests. I'm so sorry that you felt that you wasted that your time unnecessarily. I assure you that it was not meant as a trick - it was meant to be indicative of an intentional change on our part.

// <3 Corinna
